### ISSUE TITLE
Train lf accuracy higher than execution accuracy

### ISSUE THREAD

**Issue by vincentlux** [naver/sqlova#9]
Hi, 

When running the script, it is surprised to see that after several iterations (<3), the training logical form accuracy becomes higher than the training execution accuracy, which confuses me a lot. 

May I ask what is the reason behind it? I am confused for several days and could not figure it out. Thank you for any help in advance!

**Comment by whwang299** [comment]
Hi @vincentlux 

This might happen due to instability of [DBEngine class](https://github.com/naver/sqlova/blob/master/sqlnet/dbengine.py) which activates `except` in following code.
https://github.com/naver/sqlova/blob/7a8636d6d0c9a46b32b6d00eccaafeea1aab5e3b/sqlova/utils/utils_wikisql.py#L1646-L1670 

DBEngine class is modified from SQLNet code which is based on original WikiSQL evaluation code (I guess).

I'll check whether this still happens when [DBEngine from WikiSQL evaluation code](https://github.com/naver/sqlova/blob/master/wikisql/lib/dbengine.py) is employed.

Thanks!

Wonseok

**Comment by vincentlux** [comment]
Hi Wonseok,

Thanks for the quick response! This is interesting and I will also check with using the option you suggested. Thanks!

**Comment by whwang299** [comment]
@vincentlux I found the problem. It is caused by the wrong ordering of predicted where-column.

For example, when the ground truth is 
`{'sel': 1, 'conds': [[6, 0, 'at&t center 18,797'], [0, 2, 57]], 'agg': 0}`
the previous prediction in `train` function could be
`{'agg': 0, 'sel': 1, 'conds': [[0, 0, 'at&t center 18,797'], [6, 2, '57']]}`

During the test, there is no problem as this issue is caused by the use of ground-truth during the training which makes the debugging difficult. 

I have updated the [code](https://github.com/naver/sqlova/blob/03407da28328e555881c3f10850cc7fa430e3330/train.py#L292-L293). Please let me know if the problem still happens.

Wonseok
